# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{cellophane}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Phillip Koebbe"]
  s.date = %q{2011-01-09}
  s.default_executable = %q{cellophane}
  s.description = %q{Cellophane is a thin wrapper around Cucumber, making it easier to be creative when running features.}
  s.email = %q{phillip@livingdoor.net}
  s.executables = ["cellophane"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.textile"
  ]
  s.files = [
    ".cellophane.yaml",
    ".cellophane.yaml.sample",
    ".document",
    "LICENSE.txt",
    "README.textile",
    "Rakefile",
    "VERSION",
    "bin/cellophane",
    "features/feature_paths.feature",
    "features/glob_pattern.feature",
    "features/project_options.feature",
    "features/regular_expression_pattern.feature",
    "features/step_definitions.feature",
    "features/support/cellophane_methods.rb",
    "features/support/cellophane_steps.rb",
    "features/support/env.rb",
    "features/tags.feature",
    "lib/cellophane/main.rb",
    "lib/cellophane/options.rb",
    "lib/cellophane/parser.rb",
    "spec/cellophane_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/phillipkoebbe/cellophane}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{A thin wrapper around Cucumber.}
  s.test_files = [
    "spec/cellophane_spec.rb",
    "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

